### ISSUE TITLE
dataIndex 为多级点连接的时候，必填验证异常

### ISSUE THREAD

**Issue by getda** [mineadmin/MineAdmin-Vue#102]
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/25134062/48e97642-c888-4934-851c-25ca0c68e4fd)
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/25134062/a0e82a98-b5ed-4e12-9765-d3a677ce5bdb)

dataIndex 为多级点连接且formType为 select 的时候，必填验证异常

**Comment by kanyxmo** [comment]
未来修复

**Comment by getda** [comment]
> 并未复现~~ ma-form正常 ![image](https://private-user-images.githubusercontent.com/1711988/302011680-87dd8e71-e515-4d18-bfd2-6612b37b68f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MzQxNzUsIm5iZiI6MTcwNjkzMzg3NSwicGF0aCI6Ii8xNzExOTg4LzMwMjAxMTY4MC04N2RkOGU3MS1lNTE1LTRkMTgtYmZkMi02NjEyYjM3YjY4ZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMDQxNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2RjYThhYjBiMDg2OWQyZGQ5YzVlYTYzOTg2NjhmYTFhODQzM2Q2NDBmOTUwYjRiZDY4NTg4MWNhMWM0YzIxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LFG45CbFjjQU34I7ugxBjp2TMnY-PjQuQ7SAJeywrM4) ![image](https://private-user-images.githubusercontent.com/1711988/302011685-16f0e418-5527-4442-b7ac-1a59b4130723.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MzQxNzUsIm5iZiI6MTcwNjkzMzg3NSwicGF0aCI6Ii8xNzExOTg4LzMwMjAxMTY4NS0xNmYwZTQxOC01NTI3LTQ0NDItYjdhYy0xYTU5YjQxMzA3MjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMDQxNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM4YmIwNGNiZjNmM2RmZjgyMjVmMmRlYWViYWNlYWQ5YWQ1MTg5NDk5NzJhODA3YTc4Mzg2MjM0NTFkNjhjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Kz9nb0uYc7nBuh6ax0Yv1e5w5RzNlQiQtGpcmfgNv1I) ![image](https://private-user-images.githubusercontent.com/1711988/302011694-d4262c05-2504-4ffa-9677-bb4b051d2ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5MzQxNzUsIm5iZiI6MTcwNjkzMzg3NSwicGF0aCI6Ii8xNzExOTg4LzMwMjAxMTY5NC1kNDI2MmMwNS0yNTA0LTRmZmEtOTY3Ny1iYjRiMDUxZDJiYTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMDQxNzU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjU2MWVjNGJlMjEzNjhjZTNmNTU2MzViNTRkNTU4NjQ2MzA4NjJkNzBhMzEwZDQ4MWRhMmFjNGVhMWYwZTFkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Hbx3Xnr_JIeqL_xQVW6e49R0bCpAkkBhUZvr8T0WbHU)

下拉框

**Comment by kanyxmo** [comment]
修复了
