### ISSUE TITLE
form 动态添加属性的时候, dict不起作用

### ISSUE THREAD

**Issue by xhlsmile** [mineadmin/MineAdmin-Vue#103]
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/46104510/d56e9666-9c01-42b6-a564-916c81bfa77f)

![image](https://github.com/mineadmin/MineAdmin-Vue/assets/46104510/bd0c0b2f-bcbb-46df-a87d-00cae136f1d6)

**Comment by Death-Satan** [comment]
动态添加dict的数据？

**Comment by kanyxmo** [comment]
看这个 https://doc.mineadmin.com/further/front/crudComponent.html#columnservice-%E5%88%97%E6%9C%8D%E5%8A%A1%E7%B1%BB

**Comment by xhlsmile** [comment]
https://github.com/mineadmin/MineAdmin-Vue/assets/46104510/3fe29982-1ab1-4482-9bce-4bf3307ef742

@kanyxmo 我是这种

**Comment by kanyxmo** [comment]
form里也有个字典服务，看下源码就知道了
