### ISSUE TITLE
[bug] 菜单管理编辑

### ISSUE THREAD

**Issue by taobali32** [mineadmin/MineAdmin-Vue#106]
版本 2.x

当双击编辑的时候  
他是按钮类型，但是显示的内容是菜单类型的， 你再去切换在回来就没问题了
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/30717763/b46e1cc5-a50c-447e-b67f-f5e8781766ec)

这是在切换回来的好的
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/30717763/7b7109ef-8492-4d6f-85ce-d70dfae6c5cb)

**Comment by kanyxmo** [comment]
修复了  https://github.com/mineadmin/MineAdmin-Vue/commit/5f686182f4903572f6c7d61ef768854b59edf47e
