### ISSUE TITLE
疑问，curd 的 init 方法中，为 tabsHandler 增加 setTimeout 意图是什么呢？

### ISSUE THREAD

**Issue by wxfjamdc** [mineadmin/MineAdmin-Vue#108]
https://github.com/mineadmin/MineAdmin-Vue/commit/5c2dc9387add441f39842b6efe93654a49acd0a0#r138922570

这次提交增加的 setTimeout 意图是什么呢？

**Comment by kanyxmo** [comment]
等数据同步一下，因为请求字典的关系，数据还没有获取到，tab不会显示
