### ISSUE TITLE
请教一下，表单关联修改值时是否只能自己手写？

### ISSUE THREAD

**Issue by xingkoo** [mineadmin/MineAdmin-Vue#110]
使用用户选择器，
当选择一个用户时，设置单选时，获取到的数据是`[id]'，这样的数组。
但实际上往后台传输时，仅需要传输一个数字id值即可。
> 事实上，我认为，当设置`multiple: false`时，应该直接返回用户对象，如果同时`onlyId: true,`时，应该仅返回一个id。
> 考虑到此类需求，当修改信息时，需要加载显示用户名等其他信息，那么，更合适的处理是，直接返回用户对象（修改时直接加载对应的用户对象）。不论是目前的返回数组的情况，还是返回对象，合理的方案应该是可以做为辅助字段，来修改真实字段。

这时，有两种情况：
1：当选择用户确认选中后，应该可以直接修改真实用户id对应的字段。但我暂时未在项目中发现有类似实现。
2：提交前，在beforeEdit及beforeAdd中，对真实用户id字段进行修改。类似下面的代码：
```
const beforeEdit = (formData) => {
    crudRef.value.crudFormRef.form.account_owner_id = crudRef.value.crudFormRef.form.account_owner_id_helper[0].toString();
    return formData;
}
```

所以请大家提示一下，目前最合理的方案应该是什么 ？还是有哪个地方可以实现这样的需求而我没有发现？

**Comment by zds-s** [comment]
前端不太熟悉。可以加一下官网qq群

**Comment by kanyxmo** [comment]
先mark一下
