### ISSUE TITLE
curd需求增强建议

### ISSUE THREAD

**Issue by xingkoo** [mineadmin/MineAdmin-Vue#111]
有没有可能，curd的参数，表格和表单的配置，分开处理。
比如下图，表单用到了一个虚拟字段（用户选择器），一个真实字段。但在表格列中，又需要显示该创建用户的姓名信息。
此时，我需要写三个字段，然后分别设置里面各自在表格/表单中是否可用。（单独的display属性似乎不生效，需要单纯写adddisplay及editplay）。
![截屏2024-02-27 13 09 16](https://github.com/mineadmin/MineAdmin-Vue/assets/2936579/6f948cb5-bf00-4aeb-a379-1844779187c5)
![截屏2024-02-27 13 10 07](https://github.com/mineadmin/MineAdmin-Vue/assets/2936579/8ba5ce8b-25dd-41d6-913a-c69e933b6fa3)

如果分开来设置，这些数据，可以更简单的存在后端，动态请求。
类似代码生成功能中的字段，可以直接把相关配置生成json后存在后端，前端直接调用即可。

**Comment by zds-s** [comment]
你说的有点像 amis

**Comment by xingkoo** [comment]
我之前用angular写过类似的功能。mineadmin里面，把表格和表单的数据，混在一起来处理，使用的时候感觉有点混乱。但是如果区分开写，可能就是个破坏性变更了。也很麻烦。不知道作者会怎么考虑。

**Comment by xingkoo** [comment]
目前这样混合配置，真的非常不合适使用。比如`表单的 labelWidth`，字面理解，应该是放在`formOptions`中，但实际上，看了一圈代码，最后发现，要放在整个`ma-curd`的`options`中，感觉不是很合理。而且这个参数，在文档上并没有写上。
所以导致每次想要用一个功能，就需要去看源码，读一遍，非常不友好。

![截屏2024-02-27 18 13 25](https://github.com/mineadmin/MineAdmin-Vue/assets/2936579/dac44711-78f6-48de-84de-a124881276b3)

**Comment by kanyxmo** [comment]
不适合再当前基础上改，为未来未尝不可出新的版本
