### ISSUE TITLE
上传组件不显示，版本1.3.3

### ISSUE THREAD

**Issue by cruelwolfking** [mineadmin/MineAdmin-Vue#119]
上传组件编辑的时候不显示

**Comment by kanyxmo** [comment]
我这显示，有复现流程吗？

**Comment by fsg-herbie** [comment]
图片组件没问题，不显示的是文件类型在
src/components/ma-upload/components/file-upload.vue
第181行另加一行
currentItem.value.name = result.origin_name
![微信截图_20240311183558](https://github.com/mineadmin/MineAdmin-Vue/assets/14324693/84bc5a0c-5cc7-4155-abbd-a800d3c875e0)
