### ISSUE TITLE
联动 FORM 组件 cascaderItem，初始化回显时有问题 

### ISSUE THREAD

**Issue by getda** [mineadmin/MineAdmin-Vue#141]
联动 FORM 组件 cascaderItem，初始化回显时有问题 

正常A下拉框选择联动加载B是没问题的，但是如果是编辑界面，初始化A的后，B需要手动切换一次A才会有 {{key}}

**Comment by kanyxmo** [comment]
待修复吧

**Comment by getda** [comment]
> 待修复吧

这个啥时候可以修复哟😄

**Comment by kanyxmo** [comment]
最近有点忙，只能抽空了
