### ISSUE TITLE
关于使用体验

### ISSUE THREAD

**Issue by hhw2444** [mineadmin/MineAdmin-Vue#153]
每次编辑内容的时候，都需要手动刷新一下表格，才会显示修改后的内容！有什么方法可实现编辑后即刻刷新
![1](https://github.com/mineadmin/MineAdmin-Vue/assets/36981605/d88e8064-384a-4086-939f-5574793f62dd)
![2](https://github.com/mineadmin/MineAdmin-Vue/assets/36981605/17d03644-a66a-4836-8949-c56b9dbea198)

**Comment by zds-s** [comment]
submit 后调用 表格对象的 refresh 一下不就好了

**Comment by hhw2444** [comment]
> submit 后调用 表格对象的 refresh 一下不就好了

其实是想问curd组件有没有参数实现到这种方案

**Comment by hhw2444** [comment]
> submit 后调用 表格对象的 refresh 一下不就好了

看了下，formOption的viewType为tag时，就不生效了！
想用afterEdit这个方法来处理，但是调用crudRef().value.refresh，报错： crudRef,refresh is not a function
