### ISSUE TITLE
表单的input后缀openAppend怎么不起作用呢？

### ISSUE THREAD

**Issue by bingxinti** [mineadmin/MineAdmin-Vue#155]
<img width="2327" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/8444954/9873870b-d32b-4a69-88df-2cd72f9a1bc9">
openAppend: "元",

为啥不显示呢，我写法不对吗
<img width="1430" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/8444954/e33f35ac-acbf-42e7-a4c1-32989d5b1e86">

官方文档
<img width="1880" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/8444954/4e3459b2-1693-4746-9c9e-4cb52fe92991">

**Comment by kanyxmo** [comment]
1. 开启openAppend 
`openAppend: true`

2. 使用插槽
<template #inputAppend-字段名>
元
</template>

**Comment by bingxinti** [comment]
解决了感谢，我前端功底有点差。。 不好意思群主打扰了。

**Comment by bingxinti** [comment]
nice
