### ISSUE TITLE
热更新的不生效问题

### ISSUE THREAD

**Issue by one-god** [mineadmin/MineAdmin-Vue#164]
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/25094341/7ab38a05-4961-4900-8c81-ad30df9b161d)
有点不懂，一样的目录层级也一样，一个是page reload 一个hmr update,而且大部分都是hmr update，不会去更新页面，
有人知道什么问题吗

**Comment by kanyxmo** [comment]
这个应该是vite的问题，可以去vite提一下bug，这个情况偶尔出现的吧，可以试试重启项目
