### ISSUE TITLE
修改静态路由后无法访问

### ISSUE THREAD

**Issue by tiancheng-66** [mineadmin/MineAdmin-Vue#169]
目前我想实现 仪表盘 单独作为一个菜单，个人信息、消息中心 作为另一个菜单的children，如下图所示
<img width="1913" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/32589267/335803f2-3a5b-45af-ba00-219e1eaf649a">
<img width="1147" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/32589267/8d3ea2fe-a87c-4685-8f53-2d5eac12d7d2">

我修改了 store 中生成路由菜单的相关方法后 只有仪表盘能打开了，个人信息和消息中心作为静态路由无法访问了，这是为什么呢？

直接访问 /usercenter 会跳转到 /dashboard
![01bb85f92554da9097c8e0ba2547c99a](https://github.com/mineadmin/MineAdmin-Vue/assets/32589267/ebbe85c4-60c0-4c9c-af98-4e3f7c4c2553)

**Comment by zhanghangt** [comment]
打印看下路由有没有写进去，非框架问题，我先给关闭了。

**Comment by tiancheng-66** [comment]
> 打印看下路由有没有写进去，非框架问题，我先给关闭了。

抱歉打扰你，我认为这不是我路由配置的问题 因为我在layout中打印了加载页面时 router.options.routes 里面的静态路由 均是正常加载了的，但是在userStore的routers里面增加了一条路由信息（dashborad)，就会造成其余的静态路由无法访问，若不增加就可以正常访问。userStore中的数据也会影响到vue的router吗？

<img width="1426" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/32589267/37921337-1580-4f85-a922-fbdace81f10d">
