### ISSUE TITLE
MaFormModel拿不到FormRef

### ISSUE THREAD

**Issue by tiancheng-66** [mineadmin/MineAdmin-Vue#171]
<img width="1014" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/32589267/f51fc5e3-024d-40c6-bd84-6bc4afb970c7">
打印的ma-form-model 的 ref ，formRef是undefined。不能拿到form方法咋操作表单呢

**Comment by zhanghangt** [comment]
没发现问题，先确认组件调用是否正确，弹窗是否打开，或者贴上完整代码。
![微信图片_20240601160509](https://github.com/mineadmin/MineAdmin-Vue/assets/822647/0a194444-b445-4a73-b01b-b51f22ec4152)

**Comment by tiancheng-66** [comment]
```
const handleAddGroup = () => {
    // formModelRef.value.form = {}
    console.log(formModelRef.value)

    formModelRef.value.formRef.resetForm()

    formModelTitle.value = '新增'
    formModelRef.value.open({})
}
```

意思是formModelRef没有执行open的时候  formModelRef里面的formRef就是空的吗

**Comment by kanyxmo** [comment]
open未执行的时候，实际dom节点还没有生成，拿不到ref的
