### ISSUE TITLE
使用layout布局时，编辑框显示异常

### ISSUE THREAD

**Issue by quickapicn** [mineadmin/MineAdmin-Vue#174]
基于最新的main分支代码开发
layout配置如下：
```js
formOption: {
    viewType: 'modal',
    width: 800,
    layout: [
      { formType: 'grid', cols: [{ span: 12,  formList: [{ dataIndex: 'display_id' }]  }, {  span: 12, formList: [{ dataIndex: 'nick_name' }] }]},
      { formType: 'grid', cols: [{ span: 24, formList: [{ dataIndex: 'talent_level' }] }]},
      { formType: 'grid', cols: [{  span: 12, formList: [{ dataIndex: 'coopcode' }] },  { span: 12,  formList: [{ dataIndex: 'dy_uid' }] } ]},
      { formType: 'grid',  cols: [{ span: 24,  formList: [{ dataIndex: 'auth_status' }]}] },
     ]
  },
```
新增窗口是正常的，但是编辑窗口显示的字典字段会显示两次
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/171417826/75297a52-3bab-4a7b-a4ba-3a8fce9e2898)

**Comment by cqmstar** [comment]
你可以看一下src\components\ma-crud\components\form.vue这个文件，
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/44464836/1d7a7cfd-e82f-4ab8-b0a5-323c7bd121d8)
原本是这样的，在你提交这个问题前两天他们有个commit，将formColumns.value.push(item)移到下面去了，说是修复异步赋值问题，但是我测试了一下，移至下面会出现你这个问题，所以我放回来了

**Comment by zds-s** [comment]
@kanyxmo

**Comment by kanyxmo** [comment]
好的，我看一下

**Comment by kanyxmo** [comment]
之前修复别的bug，引发的新bug，已经还原了，可以更新下
