### ISSUE TITLE
[优化] children-form增加showAdd

### ISSUE THREAD

**Issue by taobali32** [mineadmin/MineAdmin-Vue#176]
<img width="657" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/30717763/613fc6aa-e61a-438c-a8f8-f395dcf62ea6">

<img width="624" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/30717763/e9562be3-180b-4978-9bf8-bd92cc6c315e">

<img width="922" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/30717763/4f872bf7-5afb-4489-b617-19b4f3319988">

**Comment by zds-s** [comment]
为啥不直接提pr

**Comment by taobali32** [comment]
> 为啥不直接提pr

懒。。

**Comment by kanyxmo** [comment]
OK，加一下
