### ISSUE TITLE
[优化] 优化请求/优化表格数据监听

### ISSUE THREAD

**Issue by taobali32** [mineadmin/MineAdmin-Vue#177]
# 1
代码这里只要一请求数据就给默认已设置选中的给干掉了，
不知道为什么这样写。应该去掉?
<img width="1037" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/30717763/c2074a00-764e-4635-8c99-1c4f6e5faaeb">

# 2

当数据改变后应该 通知上层 数据改变了,上层接不接收就是上层的事情了
<img width="1035" alt="image" src="https://github.com/mineadmin/MineAdmin-Vue/assets/30717763/aadf8e77-61b8-4efd-a63c-dcabb6b989e8">

**Comment by kanyxmo** [comment]
这里一开始没想那么多，后续绑定上v-model
