### ISSUE TITLE
【前端建议】ma-crud解耦，生成实际的add和edit页面

### ISSUE THREAD

**Issue by qzuozhu** [mineadmin/MineAdmin-Vue#185]
ma-crud太耦合了，失去了灵活性，建议生成add和edit文件。
1、如果有add和edit页面，跨栏目调用时方便很多，实际上很多时候都需要，例如：添加一个报价单，需要同时添加客户信息，公司信息，地址信息，报价的项目等，此时跨栏目调用add和edit方法就必须要把整个列表调用过来，很不方便，不灵活了。
2、add和edit页面有实际的文件时，自定义将更加便捷，例如在页面的排版上就可以随心所欲了。
为什么会有这样的想法：因为在实际应用中，很多跨栏目调用，很多页面我都要重新增加add和edit页面，失去了快速开发的意义。

**Comment by kanyxmo** [comment]
完全可以用原生组件写啊，你自己写add.vue,edit.vue然后自己引入就好了
add: {
  action:()=>{ addModal = true }
}

**Comment by qzuozhu** [comment]
而且编辑页面的字段直接生成a-form-item项是最好的，就可以随意布局了。如果用MaForm的话，不够灵活。现在就是基本上都要重新写，工作量巨大啊。

>

**Comment by zds-s** [comment]
等后面出可以自定义生成模板的时候可以考虑搞一手
