### ISSUE TITLE
【建议】编辑修改记录时，应该实时从服务器获取

### ISSUE THREAD

**Issue by qzuozhu** [mineadmin/MineAdmin-Vue#188]
列表中点击编辑按钮，并未重新在服务器获取。
因为数据库的数据已经被修改，发生了变化，点击编辑按钮不实时获取新数据的话保存就会被旧数据覆盖。

**Comment by kanyxmo** [comment]
![image](https://github.com/mineadmin/MineAdmin-Vue/assets/1711988/04469496-2875-4d3a-942f-801dcd385b51)
有的
