### ISSUE TITLE
【BUG】前端开启代码拆分后，Yarn build后混合布局的样式错乱

### ISSUE THREAD

**Issue by kurumii** [mineadmin/MineAdmin-Vue#189]
操作步骤：
步骤一：vite.config.js开启以下代码
```
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('node_modules')) {
              return id.toString().split("node_modules/")[1].split("/")[0].toString();
            }
          }
        }
      }
```
步骤二：执行yarn build命令
步骤三：进入后台，切换布局为混合
步骤四：布局异常
![1718862419973](https://github.com/mineadmin/MineAdmin-Vue/assets/30923934/0e30e831-7653-4ce7-bc99-38e41605b423)

**Comment by kanyxmo** [comment]
估计拆分拆到大动脉了，等测试看看

**Comment by fankiewing** [comment]
不要拆大动脉，参考：
`
                        if (id.includes("node_modules")) {
                            // 指定需要拆分的第三方库或模块
                            const dependenciesKeys = Object.keys(dependencies);
                            const match = dependenciesKeys.find((item) => {
                                return id.includes(item);
                            });
                            const notSplit = ['vue', '@arco-design/web-vue', 'lodash'];
                            if (match && !notSplit.includes(match)) {
                                return match;
                            }
                        }`
