### ISSUE TITLE
表格搜索的传值bug

### ISSUE THREAD

**Issue by PandaJu** [mineadmin/MineAdmin-Vue#205]
当一个页面刚刷新出来后，直接点搜索，会把为空的字段都带上传值
![image](https://github.com/user-attachments/assets/ef0f3347-bdb2-45ad-943e-62721f7b4ca4)

但是点击一次重置后，再点搜索，就正常了，不会把空字段带上传值
![image](https://github.com/user-attachments/assets/f77936bf-6228-4b4d-b2c1-2cd623a1b5e0)

**Comment by westng** [comment]
src/components/ma-crud/components/search.vue
// 过滤一下就好了；
const handlerSearch = () => {
  const filteredSearchForm = Object.keys(searchForm.value).reduce((acc, key) => {
    if (searchForm.value[key] !== '') {
      acc[key] = searchForm.value[key]
    }
    return acc
  }, {})

  emit('search', filteredSearchForm)
}
