### ISSUE TITLE
showFile的使用

### ISSUE THREAD

**Issue by tsolong** [mineadmin/MineAdmin-Vue#211]
[https://github.com/mineadmin/MineAdmin-Vue/issues/86](https://github.com/mineadmin/MineAdmin-Vue/issues/86)

你好，我也碰以如上这个问题，你的回答是在showFile方法中传入`qiniu`，传还是不行啊，而且这个config里面的地址是写死的，不支持环境区分。

```html
 <a-avatar>
    <img :src="record.avatar ? $tool.showFile(record.avatar) : $url + 'avatar.jpg'" style="object-fit: cover" />
  </a-avatar>
```

```js
tool.showFile = function(hash, defaultStorage = 'LOCAL') {
  if (hash.indexOf('.') !== -1 ) {
    return tool.viewImage(hash, defaultStorage)
  }
  let mode = tool.local.get('site_storage_mode') ? tool.local.get('site_storage_mode').toUpperCase() : defaultStorage
  return uploadConfig.storage[mode] + '/system/showFile/' + hash
}
```

就算我 调用showFile第二个参数传入`QINIU`，但你的showFile方法还是会走/system/showFile这个路径，这路径是走后端接口的服务，而当配置成QINIU时，`record.avatar`的值是一个hash，传入showFile还是一个hash，这就图片的访问图片就变成了，qiuniu.com/system/showFile/hash，而七牛的服务器根据没有system/showFile这个方法，这个方法是我们mineadmin提供的啊，怎么搞？

**Comment by jayendranar02** [comment]
hvvb

**Comment by kanyxmo** [comment]
`·tool.js` 下还有个 viewImage 函数，上传方式选择为url，不用hash和id，用这个函数直接输出图片

**Comment by tsolong** [comment]
好的，后面发现了上传组件可以设置返回url还是hash还是id，之前以为上传组件只能固定返回hash模式。
