### ISSUE TITLE
【Bug】 关于 editor 组件的显示问题

### ISSUE THREAD

**Issue by Immask-rgb** [mineadmin/MineAdmin-Vue#213]
columns使用多个formType为editor,编辑或新增有概率加载不出来editor组件 
组件应该是wang-editor,
包括系统设置添加多个富文本编辑器类型的配置项，也有概率加载不出来组件
![image](https://github.com/user-attachments/assets/28fff76c-430e-478e-a97c-f2a8a87dc16f)

**Comment by zds-s** [comment]
目前为止没印象有人反馈过这个问题，能否给个复现代码。等 @kanyxmo @People-Sea 来看看

**Comment by csdjl88** [comment]
修改/src/components/ma-editor/index.vue文件
<editor :key="props.dataIndex + editorKey" v-model="content" :init="initConfig" :id="props.dataIndex + props.id" :disabled="props.disabled"></editor>


本质上就是多个富文本同时渲染的时候，识别成同一个富文本。就会出现这个现象

**Comment by csdjl88** [comment]
`<editor :key="props.dataIndex + editorKey" v-model="content" :init="initConfig" :id="props.dataIndex + props.id" :disabled="props.disabled"></editor>`

**Comment by Immask-rgb** [comment]
是的 我自己已经处理好了
