### ISSUE TITLE
React版

### ISSUE THREAD

**Issue by jenawant** [mineadmin/MineAdmin-Vue#70]
我前端技术栈是React + AndD Pro + UmiMax，也整了版
![111111111](https://github.com/kanyxmo/MineAdmin-Vue/assets/3059179/8e9be4e9-70e1-4aca-a0a0-c195e7b24b9a)
，等空了整理整理发出来可以做个补充

**Comment by kanyxmo** [comment]
好的呢

**Comment by kanyxmo** [comment]
> 我前端技术栈是React + AndD Pro + UmiMax，也整了版 ![111111111](https://user-images.githubusercontent.com/3059179/252627840-8e9be4e9-70e1-4aca-a0a0-c195e7b24b9a.png) ，等空了整理整理发出来可以做个补充

666666
