### ISSUE TITLE
敬请阅读：特希望新增一种布局，对推广咱项目用处很大

### ISSUE THREAD

**Issue by taozhc** [mineadmin/MineAdmin-Vue#75]
您好！
         咱现在MineAdmin前端提供了多种风格，都非常友好。但我参考了很多开源前端中后台项目，甚至一些收费项目，都有这么一种布局：
       1.一级菜单在顶端，二三级在左侧
       2.顶层部门颜色可根据喜好自己设置
       
现在政府、银行、学校等企事业单位，一般要求顶层有个logo,项目名称，且一级菜单在顶层，二三级在左侧。如果把这种布局实现了，咱们的风格没有任何项目可以跟咱的MinAdmin相媲美了。在群里也有其他朋友支持此种风格。请作者认真考虑，建议实现，多谢！

可参考若依、jeesite,特别是eleadmin:  [https://plus.eleadmin.com/login](https://plus.eleadmin.com/login)  

    eleadmin风格如下：
![1](https://github.com/kanyxmo/MineAdmin-Vue/assets/140576597/cb6d2a94-7b89-4006-ab6b-0f88971f97af)

![2](https://github.com/kanyxmo/MineAdmin-Vue/assets/140576597/7ac4c30f-cc06-49dd-90c2-1ab9e7f201bf)
  
jeesite风格：
![3](https://github.com/kanyxmo/MineAdmin-Vue/assets/140576597/fdd98bf0-2776-43b3-a0fc-b414cab6104c)

若依风格：
![11](https://github.com/kanyxmo/MineAdmin-Vue/assets/140576597/4c3fca22-455e-4f1d-a8c9-3acf68d71119)

**Comment by kanyxmo** [comment]
可以的，这周加入

**Comment by kanyxmo** [comment]
https://github.com/kanyxmo/MineAdmin-Vue/commit/296836cbff9e396bb0c996710d55fb5838e9fd24
新增了混合布局

**Comment by nicesome** [comment]
<img width="1665" alt="image" src="https://github.com/kanyxmo/MineAdmin-Vue/assets/27793619/b41baf0b-38bf-403b-8524-5f0c8ff1bebb">

YYDS!!
