### ISSUE TITLE
修改上传配置为七牛云或其他oss时 , 列表页面的图片都加载失败 

### ISSUE THREAD

**Issue by zhzy-to** [mineadmin/MineAdmin-Vue#86]
加载图片的路径都是带有 /system/showFile这个 导致没有这个文件 , 而顶部右上方的个人头像加载的是本地127.0.0.1的路径

**Comment by kanyxmo** [comment]
showFile 函数第二个参数是设置类型的，传入 `qiniu` 就可以了
