### ISSUE TITLE
[BUG] 切换用户后，多标签显示异常

### ISSUE THREAD

**Issue by lushaobo** [mineadmin/MineAdmin-Vue#90]
![图片](https://github.com/mineadmin/MineAdmin-Vue/assets/5574978/fb58d621-d354-443f-9a17-5b3710e1dc41)

代码版本: 最新github代码
操作步骤：
1. 登录超级管理员
2. 点击多几个标签
3. 退出超级管理员
4. 然后登录普通管理员
5. 原先的标签会继续展示出来，正常情况下：用户退出后，标签信息应该清除。

**Comment by kanyxmo** [comment]
好的，待测试后答复

**Comment by Death-Satan** [comment]
@see [4ea1](https://github.com/mineadmin/MineAdmin-Vue/commit/804e51b09206aff43047e378e896a5c79fdf4ea1)
